PWM example
Adlink-ROS/neuron_library_example pull request #9
Opened 2020-10-15 07:44 UTC by jeffrey870517

@evshary

2020-10-15 08:11 UTC, evshary requested changes

2020-10-15 08:11 UTC, evshary commented on serial_example/nsdk_example_serial/src/mraa_uart_controller.cpp
> +const char* dev_path = "/dev/ttyttyS1";
Why do you need to modify this?

2020-10-15 08:11 UTC, evshary commented on pwm_example/README.md
> + os2 run nsdk_example_pwm pwm_control_subscriber
Typos

2020-10-27 05:50 UTC, jeffrey870517 commented
@evshary

2020-10-27 05:59 UTC, closed without merging